### PR TITLE
add doc "configure house and rooms"

### PR DESCRIPTION
**Pull request by geoffreyp**

### CODE REVIEW

**Comment by MathieuAndrade** [comment]
Great !

But it's possible to create a fr image ? 
And with the new UI please ^^

**Comment by geoffreyp** [comment]
> Greats !
> 
> But it's possible to create a fr image ?
> And with the new UI please ^^

I fix it in the last commit :)

**Comment by MathieuAndrade** [comment]
Thanks !! You're awesome guy !

**Comment by VonOx** [comment]
Hmmm screenshot need to be updated/check for every release, very time consuming.
Most of the time it is useless and in this case it is too small and it doesn't make it easier to understand.

What do you think ?

**Comment by geoffreyp** [comment]
I agree with you, I copy the documentation style of the actual documentation but yes, I think images can be optional in most cases (and it is time consuming to screenshot for EN, FR and with usefull examples)

**Comment by MathieuAndrade** [comment]
I do not agree with you ^^
While screenshots take time but it is a considerable resource for a user who would be lost in explanations !
This is also why 90% of the tutorial integrates images / screenshots.

For the problem of the versions I already thought of it and I would add a selector to adapt the documentation according to the chosen version, the images will also adapt 🙂

**Comment by VonOx** [comment]
I'm not saying that all screenshot are useless but in that case this is documentation, not tutorial / blog post.

Screenshot is small and unreadable.

**Pull request merged**
